[env:m5stack-cardputer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

extra_scripts = post:rename_bin.py

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DFASTLED_RMT_BUILTIN_DRIVER=1
    -Isrc
    -Isrc/core
    -Isrc/platform
    -Isrc/views

build_src_filter =
    +<*>
    -<platform_desktop/>

lib_deps =
    m5stack/M5Cardputer
    fastled/FastLED

[env:native]
platform = native
build_flags =
    -Isrc
    -Isrc/core
    -DNATIVE_TEST
build_src_filter =
    +<core/>
    -<core/app.cpp>
test_build_src = true
test_framework = unity
